version: '3'
services:
  rp:
    image: rp-devcontainer
    build:
      context: '.'
      args:
          VARIANT: '1.15'
          INSTALL_NODE: 'false'
    command: /bin/bash -c "while sleep 1000; do :; done"
    environment:
    - 'SKIP_AUTH=true'
    - 'PORT=5000'
    - 'MONGODB_CONNECTION_STRING=mongodb://mongoadmin:secret@mongo:27017/rpdb?authSource=admin'
    - 'MONGODB_DATABASE=rpdb'
    - 'K8S_LOCAL=true'
    - 'SUBSCRIPTION_ID=test-subscription'
    - 'RESOURCE_GROUP=test-resource-group'
    - 'RESOURCE_PROVIDER=test-resource-provider'
    - 'URL_BASE=http://localhost:5000/subscriptions/test-subscription/resourceGroups/test-resource-group/providers/Microsoft.CustomProviders/resourceProviders/test-resource-provider'
    volumes:
      - '..:/workspace/radius-rp:cached'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${HOME}${USERPROFILE}/.kube:/usr/local/share/kube-localhost'
      #- '${HOME}${USERPROFILE}/.minikube:/usr/local/share/minikube-localhost'
    depends_on:
      - mongo
    network_mode: service:mongo

  mongo:
    image: mongo
    ports:
    - '27017'
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    - MONGO_INITDB_ROOT_PASSWORD=secret
    - MONGO_INITDB_DATABASE=rpdb