# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Build and Test
on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build:
    name: Build ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
    runs-on: ${{ matrix.os }}
    env:
      GOVER: '^1.16.0'
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}
      GOPROXY: https://proxy.golang.org
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        target_arch: [arm, amd64]
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: windows-latest
            target_os: windows
          - os: macOS-latest
            target_os: darwin
        exclude:
          - os: windows-latest
            target_arch: arm
          - os: macOS-latest
            target_arch: arm
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Parse release version and set environment variables
        run: python ./.github/scripts/get_release_version.py
      - name: Make
        run: make
      - name: Run make test (unit tests)
        if: matrix.target_arch != 'arm'
        run: make test
      - name: Upload CLI binary
        uses: actions/upload-artifact@master
        with:
          name: rad_cli_${{ matrix.target_os}}_${{ matrix.target_arch}}
          path: ./dist/${{ matrix.target_os}}_${{ matrix.target_arch}}/release/
          if-no-files-found: error

  # Logic here:
  # - always do a docker build for validation
  # - tag the image as latest and with a version if the trigger was a tag
  # - tag the image with the PR version if the trigger was a PR
  # - push the image for pushes to master, or to a tag
  images:
    name: Container image build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |   
            radius.azurecr.io/radius-rp 
            radiusteam/radius-rp
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge
      - name: Docker meta - Codespaces 
        if: (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') #  only needed on push to main or tag 
        id: meta_codespaces
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            radiusteam//radius-codespaces
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: radius.azurecr.io
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.RADIUSTEAM_DOCKERHUB_USERNAME }}'
          password: '${{ secrets.RADIUSTEAM_DOCKERHUB_PASSWORD }}'
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/rp/Dockerfile  # Location of Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: | # Docker image name in each registry
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push - Codespaces
        if: (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') # push image on push to main or tag 
        uses: docker/build-push-action@v2
        with:
          context: ./.devcontainer/tutorials-codespace/
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ steps.meta_codespaces.outputs.tags }}
          labels: ${{ steps.meta_codespaces.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_tests: 
    name: Run deployment tests
    needs: [ 'build', 'images' ]
    runs-on: ubuntu-latest
    env:
      GOVER: '^1.16.0'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go ${{ env.GOVER }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVER }}
    - name: Parse release version and set environment variables
      run: python ./.github/scripts/get_release_version.py
    - name: Download release artifacts
      uses: actions/download-artifact@v2
      with:
        name: rad_cli_linux_amd64
        path: dist
    - name: Print assets (for santity)
      run: |
        echo "Asserts are in: $(cd "$(dirname ".")" && pwd)/$(basename ".")"
        ls -R
      working-directory: dist
    - name: Make rad executable
      run: chmod +x rad
      working-directory: dist
    - name: az CLI login
      run: |
        az login --service-principal \
          --username ${{ secrets.INTEGRATION_TEST_SP_APP_ID }} \
          --password ${{ secrets.INTEGRATION_TEST_SP_PASSWORD }} \
          --tenant ${{ secrets.INTEGRATION_TEST_TENANT_ID }}
      # We select a test environment here and load it into the default 
      # radius config so that it will be used by tests
    - name: Reserve test environment
      id: reserve
      run: |
        export AZURE_TENANT_ID=${{ secrets.INTEGRATION_TEST_TENANT_ID }}
        export AZURE_CLIENT_ID=${{ secrets.INTEGRATION_TEST_SP_APP_ID }}
        export AZURE_CLIENT_SECRET=${{ secrets.INTEGRATION_TEST_SP_PASSWORD }}
        mkdir ~/.rad
        go run cmd/testenv/main.go \
          reserve \
          --accountkey ${{ secrets.INTEGRATION_TEST_STORAGE_KEY }} \
          --accountname ${{ secrets.INTEGRATION_TEST_STORAGE_NAME }} \
          --tablename environments \
          --configpath ~/.rad/config.yaml \
          --timeout 60
        cat ~/.rad/config.yaml
    - name: Merge Kubernetes credentials
      run: |
        export PATH=$GITHUB_WORKSPACE/dist:$PATH
        export AZURE_TENANT_ID=${{ secrets.INTEGRATION_TEST_TENANT_ID }}
        export AZURE_CLIENT_ID=${{ secrets.INTEGRATION_TEST_SP_APP_ID }}
        export AZURE_CLIENT_SECRET=${{ secrets.INTEGRATION_TEST_SP_PASSWORD }}
        rad env merge-credentials
    - name: Update test environment RP
      run: |
        export AZURE_TENANT_ID=${{ secrets.INTEGRATION_TEST_TENANT_ID }}
        export AZURE_CLIENT_ID=${{ secrets.INTEGRATION_TEST_SP_APP_ID }}
        export AZURE_CLIENT_SECRET=${{ secrets.INTEGRATION_TEST_SP_PASSWORD }}
        go run cmd/testenv/main.go \
          update-rp \
          --configpath ~/.rad/config.yaml \
          --image radiusteam/radius-rp:${{ env.REL_CHANNEL }}
    - name: Run deploy tests
      run: |
        export PATH=$GITHUB_WORKSPACE/dist:$PATH
        export AZURE_TENANT_ID=${{ secrets.INTEGRATION_TEST_TENANT_ID }}
        export AZURE_CLIENT_ID=${{ secrets.INTEGRATION_TEST_SP_APP_ID }}
        export AZURE_CLIENT_SECRET=${{ secrets.INTEGRATION_TEST_SP_PASSWORD }}
        cd $GITHUB_WORKSPACE
        echo "PATH is $PATH"
        which rad || { echo "cannot find rad"; exit 1; }
        make deploy-tests
    - name: Release test environment
      if: ${{ success() || steps.reserve.outcome == 'success' }}
      run: |
        go run cmd/testenv/main.go \
          release \
          --accountkey ${{ secrets.INTEGRATION_TEST_STORAGE_KEY }} \
          --accountname ${{ secrets.INTEGRATION_TEST_STORAGE_NAME }} \
          --tablename environments \
          --configpath ~/.rad/config.yaml

  publish:
    name: Publish rad CLI binaries
    needs: [ 'build' ] # may want to add needs 'deploy_tests' as well in the future
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') # upload on push to main or tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse release version and set environment variables
        run: python ./.github/scripts/get_release_version.py
      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: rad_cli_darwin_amd64
          path: rad_cli_darwin_amd64
      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: rad_cli_linux_amd64
          path: rad_cli_linux_amd64
      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: rad_cli_windows_amd64
          path: rad_cli_windows_amd64
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: rad_cli_darwin_amd64
          container_name: 'tools'
          connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
          sync: true
          extra_args: '--destination-path rad/${{ env.REL_VERSION }}/macos-x64/ --pattern rad'
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: rad_cli_linux_amd64
          container_name: 'tools'
          connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
          sync: true
          extra_args: '--destination-path rad/${{ env.REL_CHANNEL }}/linux-x64/ --pattern rad'
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: rad_cli_windows_amd64
          container_name: 'tools'
          connection_string: ${{ secrets.ASSETS_STORAGE_CONNECTION_STRING }}
          sync: true
          extra_args: '--destination-path rad/${{ env.REL_VERSION }}/windows-x64/ --pattern rad.exe'

